# image will be published to ghcr.io/<user>/<name>
name: ptinopedila-homelab
# description will be included in the image's metadata
description: "Bluefin main for economists (soon)."

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest

# list of modules, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common_modules/common-packages.yml
  - from-file: common_modules/common-scripts.yml
  - from-file: common_modules/common-files.yml
  - from-file: common_modules/gnome.yml
  - from-file: common_modules/desktop-minimal.yml

  - from-file: common_modules/dynare.yml
  - from-file: common_modules/matlab.yml
  - from-file: common_modules/r.yml
  - from-file: common_modules/stata-packages.yml
  - from-file: common_modules/stata-script.yml
  - from-file: common_modules/tex.yml
  - from-file: common_modules/ws.yml

  - from-file: common_modules/dropbox.yml
  - from-file: common_modules/home.yml

  - from-file: common_modules/secureblue/common-scripts.yml

  - type: yafti
