type: rpm-ostree
repos: 
  - https://copr.fedorainfracloud.org/coprs/iucar/cran/repo/fedora-39/iucar-cran-fedora-39.repo
install:
  - R
  - R-CoprManager
  # - R-CRAN-abind
  # - R-CRAN-astsa
  # - R-CRAN-backports
  # - R-CRAN-base64enc
  # - R-CRAN-bit
  # - R-CRAN-bit64
  # - R-CRAN-boot
  # - R-CRAN-broom
  # - R-CRAN-car
  # - R-CRAN-carData
  # - R-CRAN-caret
  # - R-CRAN-cellranger
  # - R-CRAN-checkmate
  # - R-CRAN-class
  # - R-CRAN-cli
  # - R-CRAN-clipr
  # - R-CRAN-codetools
  # - R-CRAN-cointReg
  # - R-CRAN-colorspace
  # - R-CRAN-conquer
  # - R-CRAN-crayon
  # - R-CRAN-crayon
  # - R-CRAN-curl
  # - R-CRAN-deSolve
  # - R-CRAN-devtools
  # - R-CRAN-digest
  # - R-CRAN-digest
  # - R-CRAN-dplyr
  # - R-CRAN-DynareR
  # - R-CRAN-e1071
  # - R-CRAN-easypackages
  # - R-CRAN-ellipsis
  # - R-CRAN-estimatr
  # - R-CRAN-eurostat
  # - R-CRAN-evaluate
  # - R-CRAN-evaluate
  # - R-CRAN-fansi
  # - R-CRAN-farver
  # - R-CRAN-fastmap
  # - R-CRAN-forcats
  # - R-CRAN-foreach
  # - R-CRAN-forecast
  # - R-CRAN-foreign
  # - R-CRAN-fredr
  # - R-CRAN-future
  # - R-CRAN-generics
  # - R-CRAN-ggplot2
  # - R-CRAN-glmnet
  # - R-CRAN-globals
  # - R-CRAN-glue
  # - R-CRAN-gower
  # - R-CRAN-gtable
  # - R-CRAN-haven
  # - R-CRAN-here
  # - R-CRAN-highr
  # - R-CRAN-Hmisc
  # - R-CRAN-hms
  # - R-CRAN-htmltools
  # - R-CRAN-httpgd
  # - R-CRAN-ipred
  # - R-CRAN-IRdisplay
  # - R-CRAN-IRkernel
  # - R-CRAN-isoband
  # - R-CRAN-iterators
  # - R-CRAN-jquerylib
  # - R-CRAN-jsonlite
  # - R-CRAN-knitr
  # - R-CRAN-labeling
  # - R-CRAN-languageserver
  # - R-CRAN-lattice
  # - R-CRAN-lava
  # - R-CRAN-lifecycle
  # - R-CRAN-listenv
  # - R-CRAN-lme4
  # - R-CRAN-lmtest
  # - R-CRAN-lubridate
  # - R-CRAN-magrittr
  # - R-CRAN-markdown
  # - R-CRAN-MASS
  # - R-CRAN-Matrix
  # - R-CRAN-MatrixModels
  # - R-CRAN-matrixStats
  # - R-CRAN-Metrics
  # - R-CRAN-mgcv
  # - R-CRAN-minqa
  # - R-CRAN-mnormt
  # - R-CRAN-ModelMetrics
  # - R-CRAN-modopt.matlab
  # - R-CRAN-munsell
  # - R-CRAN-nlme
  # - R-CRAN-nloptr
  # - R-CRAN-nnet
  # - R-CRAN-numDeriv
  # - R-CRAN-openxlsx
  # - R-CRAN-orcutt
  # - R-CRAN-parallelly
  # - R-CRAN-pbdZMQ
  # - R-CRAN-pbkrtest
  # - R-CRAN-pillar
  # - R-CRAN-pkgconfig
  # - R-CRAN-plm
  # - R-CRAN-plotrix
  # - R-CRAN-pls
  # - R-CRAN-plyr
  # - R-CRAN-png
  # - R-CRAN-pROC
  # - R-CRAN-prodlim
  # - R-CRAN-progressr
  # - R-CRAN-proxy
  # - R-CRAN-psych
  # - R-CRAN-purrr
  # - R-CRAN-quadprog
  # - R-CRAN-quantmod
  # - R-CRAN-quantreg
  # - R-CRAN-R.matlab
  # - R-CRAN-R6
  # - R-CRAN-rappdirs
  # - R-CRAN-RColorBrewer
  # - R-CRAN-Rcpp
  # - R-CRAN-rdrobust
  # - R-CRAN-readr
  # - R-CRAN-readstata13
  # - R-CRAN-readxl
  # - R-CRAN-recipes
  # - R-CRAN-rematch
  # - R-CRAN-repr
  # - R-CRAN-reshape2
  # - R-CRAN-reticulate
  # - R-CRAN-rio
  # - R-CRAN-rio
  # - R-CRAN-rlang
  # - R-CRAN-rmarkdown
  # - R-CRAN-rpart
  # - R-CRAN-rprojroot
  # - R-CRAN-sandwich
  # - R-CRAN-scales
  # - R-CRAN-seastests
  # - R-CRAN-sp
  # - R-CRAN-SparseM
  # - R-CRAN-splitstackshape
  # - R-CRAN-SQUAREM
  # - R-CRAN-statar
  # - R-CRAN-stringi
  # - R-CRAN-stringr
  # - R-CRAN-strucchange
  # - R-CRAN-survival
  # - R-CRAN-tempdisagg
  # - R-CRAN-tibble
  # - R-CRAN-tidyr
  # - R-CRAN-tidyselect
  # - R-CRAN-timeDate
  # - R-CRAN-tinytex
  # - R-CRAN-tmvnsim
  # - R-CRAN-tsDyn
  # - R-CRAN-tseries
  # - R-CRAN-tseriesChaos
  # - R-CRAN-tsoutliers
  # - R-CRAN-TTR
  # - R-CRAN-tzdb
  # - R-CRAN-utf8
  # - R-CRAN-uuid
  # - R-CRAN-vars
  # - R-CRAN-vctrs
  # - R-CRAN-viridisLite
  # - R-CRAN-vroom
  # - R-CRAN-withr
  # - R-CRAN-wooldridge
  # - R-CRAN-writexl
  # - R-CRAN-xfun
  # - R-CRAN-xts
  # - R-CRAN-yaml
  # - R-CRAN-zip
  # - R-CRAN-zoo
  - rstudio-desktop
  # - R-CRAN-maptools  Consider using 'sf' or 'terra' instead.
